architecture:
  - Conv2d:
      kernel_size: 3
      in_channels: 3
      out_channels: 16
      stride: 1
      padding: same
  - MaxPool2d:
      kernel_size: 2
      stride: 2
  - BatchNorm2d:
      args: [16]
  - ReLU:
  - Conv2d:
      kernel_size: 3
      in_channels: 16
      out_channels: 32
      stride: 1
      padding: same
  - MaxPool2d:
      kernel_size: 2
      stride: 2
  - BatchNorm2d:
      args: [32]
  - ReLU:
  - Flatten:
  - Linear:
      args: [24576, 128]
      alias: N_FT_LAYER
  - ReLU:
  - Linear:
      args: [128, 4]
      alias: CLS_LAYER
  - Softmax: